### ISSUE TITLE
Error - cannot read port of undefined

### ISSUE THREAD

**Issue by indrajitdan** [quasarframework/quasar-template-ssr#1]
I did 
quasar init ssr qsr-ssr-app
cd qsr-ssr-app
npm i
quasar dev
At the last step getting error
.npm-global/lib/node_modules/quasar-cli/bin/quasar-dev:125
  return qfs.exists(configFile) ? require(configFile).dev.port : 8080

TypeError: Cannot read property 'port' of undefined

**Comment by rstoenescu** [comment]
This is marked as WIP. Do not use it yet.
